# docker-compose production overrides
---
version: "3.4"
services:
  web:
    restart: unless-stopped
    environment:
      # Number of worker processes for handling requests
      # http://docs.gunicorn.org/en/stable/settings.html#workers
      WEB_CONCURRENCY: 3

  postgres:
    restart: unless-stopped
