version: "3.4"
x-service-base: &service_base
  environment: &psql_vars
    PGDATABASE: ${PGDATABASE:-cdr}
    PGHOST: postgres
    PGPASSWORD: ""
    PGUSER: postgres

services:
  web:
    environment:
      <<: *psql_vars
      PROXYPATH: ${PROXYPATH:-}

    build: .
    ports:
      - "${EXTERNAL_PORT:-5000}:${PORT:-5000}"
    volumes:
      - .:/cdr
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    <<: *service_base
    environment:
      POSTGRES_DB: ${PGDATABASE:-cdr}
    image: postgres:11
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
