version: "3.4"
x-service-base: &service_base
  environment:
    MONGOHOST: mongo
    PGDATABASE: cdr
    PGHOST: postgres
    PGPASSWORD: ""
    PGUSER: postgres

services:
  web:
    <<: *service_base
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/cdr
    depends_on:
        - mongo
        - postgres

  mongo:
    image: mongo:4.2-bionic
    restart: always
    command: --directoryperdb --enableFreeMonitoring off
    volumes:
      - mongo-data:/data/db
      - /opt/docker-compose-mongo/restore:/restore

  postgres:
    <<: *service_base
    environment:
      POSTGRES_DB: ${PGDATABASE:-cdr}
    image: postgres:11
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data: {}
  postgres-data: {}
